# Generated by Django 3.1.1 on 2021-05-19 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cowin_alert', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slots',
            name='data',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
