# Generated by Django 3.1.1 on 2021-05-20 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cowin_alert', '0003_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='slots',
            name='slot_district',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cowin_alert.district'),
            preserve_default=False,
        ),
    ]
