# Generated by Django 3.1.1 on 2021-05-21 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cowin_alert', '0004_slots_slot_district'),
    ]

    operations = [
        migrations.CreateModel(
            name='Center',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center_name', models.CharField(max_length=100)),
                ('center_slots', models.IntegerField()),
                ('center_district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cowin_alert.district')),
            ],
        ),
        migrations.DeleteModel(
            name='Slots',
        ),
    ]
