# Generated by Django 3.1.1 on 2021-05-21 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cowin_alert', '0006_district_district_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='district',
            name='user_district',
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cowin_alert.district')),
            ],
        ),
    ]
