# Generated by Django 3.1.1 on 2021-05-21 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cowin_alert', '0007_auto_20210521_1011'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
