# Generated by Django 3.1.1 on 2021-05-24 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cowin_alert', '0013_user_details_dose_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='center',
            name='center_slots_dose1',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
