# Generated by Django 3.1.1 on 2021-05-25 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cowin_alert', '0014_auto_20210524_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='session_id',
            field=models.TextField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
