# Generated by Django 3.1.1 on 2021-05-26 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cowin_alert', '0016_auto_20210526_1005'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slots_dose1', models.IntegerField(blank=True, default=0)),
                ('slots_dose2', models.IntegerField(blank=True, default=0)),
                ('center_slots', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cowin_alert.center')),
            ],
        ),
        migrations.RemoveField(
            model_name='slots_dose2',
            name='center_slots',
        ),
        migrations.DeleteModel(
            name='Slots_dose1',
        ),
        migrations.DeleteModel(
            name='Slots_dose2',
        ),
    ]
