# Generated by Django 3.1.1 on 2021-05-26 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cowin_alert', '0017_auto_20210526_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='slots',
            name='session_id',
            field=models.TextField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Session_id',
        ),
    ]
