# Generated by Django 3.1.1 on 2021-05-27 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cowin_alert', '0019_auto_20210527_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='center_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
